### ISSUE TITLE
Uses the GIT SHA commit rather than the CircleCI SHA for tagging the ECR image

### ISSUE THREAD

**Issue by jcgarciam-signavio** [signavio/circleci-aws-ecr-eks-orb#7]
IHMO its better to tag the image with the GIT commit as it makes it easier later to find out to which commit does this images refers to.

https://github.com/signavio/circleci-aws-ecr-eks-orb/blob/5085324bb7cc16b48cd926c6b523d95f12f71b03/src/%40orb.yml#L46

**Comment by svenwb** [comment]
Isn't that the case? Based on https://circleci.com/docs/2.0/env-vars/

```
CIRCLE_SHA1: The SHA1 hash of the last commit of the current build.
```

**Comment by jcgarciam-signavio** [comment]
Thank you @svenwb , i didn't realize (nor double check that before writing this here).
